// AUTO-GENERATED by `bun run scan`. Edit annotations in registry/annotations.ts, not here.
import { z } from "zod";

import type { OperationDef } from "./types";

export const complianceOps: OperationDef[] = [
  {
    id: "compliance.overview",
    facade: "compliance",
    method: "GET",
    path: "/api/hcm/compliance/overview",
    pathParams: [],
    query: z.object({}).passthrough(),
    summary: "GET /api/hcm/compliance/overview",
  },
  {
    id: "compliance.policies",
    facade: "compliance",
    method: "GET",
    path: "/api/hcm/compliance/policies",
    pathParams: [],
    query: z.object({}).passthrough(),
    summary: "GET /api/hcm/compliance/policies",
  },
  {
    id: "compliance.requirements",
    facade: "compliance",
    method: "GET",
    path: "/api/hcm/compliance/requirements",
    pathParams: [],
    query: z.object({}).passthrough(),
    summary: "GET /api/hcm/compliance/requirements",
  },
];
