// AUTO-GENERATED by `bun run scan`.

import { adminOps } from "./admin";
import { analyticsOps } from "./analytics";
import { applyAnnotations } from "./annotations";
import { attendanceOps } from "./attendance";
import { complianceOps } from "./compliance";
import { employeesOps } from "./employees";
import { engagementOps } from "./engagement";
import { essOps } from "./ess";
import { leaveOps } from "./leave";
import { masterdataOps } from "./masterdata";
import { org_developmentOps } from "./org_development";
import { payrollOps } from "./payroll";
import { performanceOps } from "./performance";
import { recruitmentOps } from "./recruitment";
import { schedulingOps } from "./scheduling";
import { talentOps } from "./talent";
import { trainingOps } from "./training";
import type { OperationDef } from "./types";

export const REGISTRY: Record<string, OperationDef[]> = applyAnnotations({
  employees: employeesOps,
  attendance: attendanceOps,
  leave: leaveOps,
  scheduling: schedulingOps,
  payroll: payrollOps,
  performance: performanceOps,
  talent: talentOps,
  recruitment: recruitmentOps,
  training: trainingOps,
  compliance: complianceOps,
  engagement: engagementOps,
  org_development: org_developmentOps,
  analytics: analyticsOps,
  ess: essOps,
  masterdata: masterdataOps,
  admin: adminOps,
});
