// AUTO-GENERATED by `bun run scan`. Edit annotations in registry/annotations.ts, not here.
import { z } from "zod";

import type { OperationDef } from "./types";

export const leaveOps: OperationDef[] = [
  {
    id: "leave.root",
    facade: "leave",
    method: "GET",
    path: "/api/hcm/leave-accrual",
    pathParams: [],
    query: z.object({}).passthrough(),
    summary: "GET /api/hcm/leave-accrual",
  },
  {
    id: "leave.root_2",
    facade: "leave",
    method: "GET",
    path: "/api/hcm/medical-certificates",
    pathParams: [],
    query: z.object({}).passthrough(),
    summary: "GET /api/hcm/medical-certificates",
  },
  {
    id: "leave.root_3",
    facade: "leave",
    method: "GET",
    path: "/api/hcm/leave",
    pathParams: [],
    query: z.object({}).passthrough(),
    summary: "GET /api/hcm/leave",
  },
  {
    id: "leave.root_by_id",
    facade: "leave",
    method: "GET",
    path: "/api/hcm/medical-certificates/{id}",
    pathParams: ["id"],
    query: z.object({}).passthrough(),
    summary: "GET /api/hcm/medical-certificates/{id}",
  },
  {
    id: "leave.root_by_id_2",
    facade: "leave",
    method: "GET",
    path: "/api/hcm/leave/{id}",
    pathParams: ["id"],
    query: z.object({}).passthrough(),
    summary: "GET /api/hcm/leave/{id}",
  },
];
