// AUTO-GENERATED by `bun run scan`. Edit annotations in registry/annotations.ts, not here.
import { z } from "zod";

import type { OperationDef } from "./types";

export const masterdataOps: OperationDef[] = [
  {
    id: "masterdata.lov",
    facade: "masterdata",
    method: "GET",
    path: "/api/masterdata/lov",
    pathParams: [],
    query: z.object({}).passthrough(),
    summary: "GET /api/masterdata/lov",
  },
];
