// AUTO-GENERATED by `bun run scan`. Edit annotations in registry/annotations.ts, not here.
import { z } from "zod";

import type { OperationDef } from "./types";

export const org_developmentOps: OperationDef[] = [
  {
    id: "org_development.analytics",
    facade: "org_development",
    method: "GET",
    path: "/api/hcm/org-development/analytics",
    pathParams: [],
    query: z.object({}).passthrough(),
    summary: "GET /api/hcm/org-development/analytics",
  },
  {
    id: "org_development.departments_tree",
    facade: "org_development",
    method: "GET",
    path: "/api/hcm/org/departments/tree",
    pathParams: [],
    query: z.object({}).passthrough(),
    summary: "GET /api/hcm/org/departments/tree",
  },
  {
    id: "org_development.root",
    facade: "org_development",
    method: "GET",
    path: "/api/hcm/org-chart",
    pathParams: [],
    query: z.object({}).passthrough(),
    summary: "GET /api/hcm/org-chart",
  },
  {
    id: "org_development.scenarios",
    facade: "org_development",
    method: "GET",
    path: "/api/hcm/org-development/scenarios",
    pathParams: [],
    query: z.object({}).passthrough(),
    summary: "GET /api/hcm/org-development/scenarios",
  },
];
