import { scanDir } from "../src/registry/scan";
import { FACADE_NAMES } from "../src/registry/types";
import { spawnSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const apiDir = resolve(here, "../../backend/src/app/api");
if (!existsSync(apiDir)) throw new Error(`backend api dir not found: ${apiDir}`);

const ops = scanDir(apiDir);
const byFacade = new Map<string, typeof ops>();
for (const f of FACADE_NAMES) byFacade.set(f, []);
for (const op of ops) byFacade.get(op.facade)?.push(op);

const regDir = resolve(here, "../src/registry");

function serializeOp(op: (typeof ops)[number]): string {
  return `  {
    id: ${JSON.stringify(op.id)},
    facade: ${JSON.stringify(op.facade)},
    method: "GET",
    path: ${JSON.stringify(op.path)},
    pathParams: ${JSON.stringify(op.pathParams)},
    query: z.object({}).passthrough(),
    summary: ${JSON.stringify(op.summary)},
  },`;
}

for (const facade of FACADE_NAMES) {
  const list = byFacade.get(facade) ?? [];
  const body = `// AUTO-GENERATED by \`bun run scan\`. Edit annotations in registry/annotations.ts, not here.
import { z } from "zod";
import type { OperationDef } from "./types";

export const ${facade}Ops: OperationDef[] = [
${list.map(serializeOp).join("\n")}
];
`;
  writeFileSync(join(regDir, `${facade}.ts`), body);
}

const indexBody = `// AUTO-GENERATED by \`bun run scan\`.
import type { OperationDef } from "./types";
import { applyAnnotations } from "./annotations";
${FACADE_NAMES.map((f) => `import { ${f}Ops } from "./${f}";`).join("\n")}

export const REGISTRY: Record<string, OperationDef[]> = applyAnnotations({
${FACADE_NAMES.map((f) => `  ${f}: ${f}Ops,`).join("\n")}
});
`;
writeFileSync(join(regDir, "index.ts"), indexBody);

// Format the generated files so `bun run scan` output is biome-clean and idempotent.
spawnSync("bunx", ["biome", "check", "--write", regDir], { stdio: "inherit" });

console.error(`scanned ${ops.length} GET routes across ${FACADE_NAMES.length} facades`);
for (const f of FACADE_NAMES) console.error(`  ${f}: ${byFacade.get(f)?.length ?? 0}`);
